// Generated by CoffeeScript 1.3.1
var Filesystem, ZfsAnalyser, exports, normalizeBytes;

Filesystem = require('../../zpool/filesystem');

normalizeBytes = function(input) {
  var e, nil, numeric, pattern, suffix, _i, _len, _ref, _ref1;
  _ref = ['', 'K', 'M', 'G', 'T', 'P', 'E', 'Z', 'Y'];
  for (e = _i = 0, _len = _ref.length; _i < _len; e = ++_i) {
    suffix = _ref[e];
    pattern = new RegExp("^([+-]?[\\d.]+)" + suffix + "$", 'i');
    if (pattern.test(input)) {
      _ref1 = pattern.exec(input), nil = _ref1[0], numeric = _ref1[1];
      return Math.round(numeric * Math.pow(1024, e));
    }
  }
  return 0;
};

ZfsAnalyser = (function() {

  ZfsAnalyser.name = 'ZfsAnalyser';

  function ZfsAnalyser(pool) {
    this.pool = pool;
  }

  ZfsAnalyser.prototype.parse = function(lines) {
    var available, filesystems, fs, fsSize, i, isNonLeafFilesystem, lastFs, line, name, poolName, referenced, snapshots, used, usedBySnapshot, _i, _ref, _ref1;
    snapshots = new Filesystem('@snapshots', 0);
    lastFs = {
      name: '/'
    };
    filesystems = [];
    poolName = this.pool.name;
    for (i = _i = _ref = lines.length - 1; _ref <= 0 ? _i <= 0 : _i >= 0; i = _ref <= 0 ? ++_i : --_i) {
      line = lines[i];
      if (!line) {
        continue;
      }
      _ref1 = line.split(/\s+/), name = _ref1[0], used = _ref1[1], available = _ref1[2], referenced = _ref1[3], usedBySnapshot = _ref1[4];
      snapshots.size += normalizeBytes(usedBySnapshot);
      isNonLeafFilesystem = name !== poolName && lastFs.name.indexOf(name) === 0;
      if (isNonLeafFilesystem) {
        continue;
      }
      if (name === poolName) {
        this.pool.size = normalizeBytes(used) + normalizeBytes(available);
        if (lines.length !== 1) {
          continue;
        }
      }
      fsSize = normalizeBytes(referenced);
      this.pool.allocated += fsSize;
      fs = new Filesystem(name, fsSize);
      lastFs = fs;
      this.pool.addFilesystem(fs);
    }
    this.pool.addFilesystem(snapshots);
    return this.pool;
  };

  return ZfsAnalyser;

})();

module.exports = exports = ZfsAnalyser;
